// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ParallaxLayerMap","status":true,"description":"多層レイヤー一枚絵マッププラグイン","parameters":{}},
{"name":"Foreground","status":true,"description":"マップに合わせてスクロールする近景の設定(Ver1.0.1)","parameters":{}}
];
